version: '3.8'
services:
  users:
    container_name: users
    volumes:
      - ./backend/users:/usr/src/users_app
      - /usr/src/users_app/node_modules
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
    ports:
      - 3001:3001
    depends_on:
      - database
  orchestrator:
    container_name: orchestrator
    volumes:
      - ./backend/orchestrator:/usr/src/orchestrator_app
      - /usr/src/orchestrator_app/node_modules
    build:
      context: ./backend/orchestrator
      dockerfile: Dockerfile
    environment:
      - USER_SERVICE_HOST=users
    ports:
      - 3000:3000
    depends_on:
      - database
      

  database:
    image: postgres
    container_name: database
    restart: on-failure
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: chat-dev
    ports:
      - 5432:5432