version: '3.8'
services:
  frontend:
    container_name: app
    image: app
    build:
      context: ./frontend
      target: debug
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - database
      - users
      - orchestrator
  orchestrator:
    container_name: orchestrator
    image: orchestrator
    build:
      context: ./backend/orchestrator
      target: debug
    ports:
      - 3000:3000
    environment:
      - USER_SERVICE_HOST=users
    volumes:
      - ./backend/orchestrator:/orchestrator
      - /orchestrator/node_modules
    depends_on:
      - users
      - database
  users:
    container_name: users
    image: users
    volumes:
      - ./backend/users:/users
      - /users/node_modules
    build:
      context: ./backend/users
      target: debug
    environment:
      - DB_HOST=database
      - CORS_ALLOWED_ORIGIN_HOST=orchestrator
    ports:
      - 3001:3001
    depends_on:
      - database  

  database:
    image: postgres
    container_name: database
    restart: on-failure
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: chat-dev
    ports:
      - 5432:5432