version: '3.8'
services:
  users:
    container_name: users_service
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - database
  orchestrator:
    container_name: orchestrator
    build:
      context: ./backend/orchestrator
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
      

  database:
    image: mongo:7.0.4
    container_name: mongodb
    ports:
      - 27017:27017

